[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { path = "../game" }
network = { path = "../network" }
server = { path = "../server" }
log = "0.4"
env_logger = { version = "0.9", default-features = false, features = ["humantime"] }
sdl2 = "0.35"
winapi = { version = "0.3.9", features = ["shellscalingapi"] }
bytemuck = { version = "1.9", features = ["derive"] }
glam = "0.20"
ash = "0.37"
image = { version = "0.24", default-features = false, features = ["png"] }
serde = { version = "1.0" }
serde_yaml = { version = "0.8" }