{
 "title": "Farmisto",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "FPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(app_frame[10s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Render Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gameplay_animation_seconds_sum[10s]) / rate(gameplay_animation_seconds_count[10s])",
     "legendFormat": "animation"
    },
    {
     "expr": "rate(gameplay_draw_request_seconds_sum[10s]) / rate(gameplay_draw_request_seconds_count[10s])",
     "legendFormat": "draw request"
    },
    {
     "expr": "rate(sprites_render_seconds_sum[10s]) / rate(sprites_render_seconds_count[10s])",
     "legendFormat": "render"
    }
   ]
  },
  {
   "title": "Shader Data Describes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "irate(shader_describes_total{cache=\"hit\"}[2s])",
     "legendFormat": "hits per second"
    },
    {
     "expr": "shader_describes_total{cache=\"miss\"}",
     "legendFormat": "total miss"
    }
   ]
  },
  {
   "title": "Top 10 Texture Loading",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort(sum(texture_loading_seconds_sum / texture_loading_seconds_count) by (path)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Asset Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(asset_requests_total) by (type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}