global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'host'
    static_configs:
      - targets: [ 'host.docker.internal:9092' ]
  - job_name: 'client'
    static_configs:
      - targets: [ 'host.docker.internal:9091' ]
