[package]
name = "datamap"
version = "0.1.0"
edition = "2021"


[dependencies]
rusqlite = { version = "0.27", default-features = false, features = ["serde_json", "bundled"] }
log = "0.4"
serde_json = { version = "1.0" }
serde = { version = "1.0" }