[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { path = "../game" }
log = "0.4"
serde = { version = "1.0" }
bincode = { version = "2.0.0-rc.2", features = ["serde"] }
prometheus = { version = "0.13.3" }
lazy_static = "1.4.0"
snap = "1"