[package]
name = "player"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { path = "../game" }
log = "0.4"
env_logger = { version = "0.9", default-features = false, features = ["humantime"] }
sdl2 = "0.35"
winapi = {version = "0.3.9", features = ["shellscalingapi"]}