[package]
name = "player"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = { version = "0.9", default-features = false, features = ["humantime"] }
game = { path = "../game" }