[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { path = "../game" }
network = { path = "../network" }
datamap = { path = "../datamap" }
log = "0.4"
prometheus = { version = "0.13.3" }
lazy_static = "1.4.0"