[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { path = "../game" }
network = { path = "../network" }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
http = "0.2"
regex = "1"
tungstenite = { version="0.18" }