name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout database for tests
      run: git lfs pull assets/database.sqlite
    - name: Prepare Rust
      run: cargo --version
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: Prepare Python
      run: python --version
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements.txt') }}

    - name: Run unit tests
      run: cargo test

    - name: Build testing lib
      run: cargo build --package testing --release

    - name: Install Python requirements
      run: pip3 install -r tests/requirements.txt

    - name: Run BDD tests
      run: cd tests && behave .
