name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bdd:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare Rust
      run: cargo --version
    - name: Prepare Python
      run: python --version
    - name: Install requirements
      run: pip3 install -r tests/requirements.txt
    - name: Run tests
      run: behave tests
